name: Node.js CI

on:
  push:
    branches:
      - "main" # demo branch
      - "prod" # production branch

jobs:
  deploy-demo:
    runs-on: [self-hosted, demo]
    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      # ðŸŸ¡ Ø¥Ù†Ø´Ø§Ø¡ Ù…Ù„Ù .env Ø­Ø³Ø¨ Ø§Ù„ÙØ±Ø¹
      - name: Create .env file for Demo
        if: github.ref == 'refs/heads/main'
        run: echo "${{ vars.ENV_DEMO }}" > .env

      - name: Build project
        run: pnpm run build --if-present

      - run: pm2 startOrRestart ecosystem.config.cjs

  deploy-prod:
    runs-on: [self-hosted, prod]
    if: github.ref == 'refs/heads/prod'

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      # ðŸŸ¡ Ø¥Ù†Ø´Ø§Ø¡ Ù…Ù„Ù .env Ø­Ø³Ø¨ Ø§Ù„ÙØ±Ø¹
      - name: Create .env file for Production
        if: github.ref == 'refs/heads/prod'
        run: echo "${{ vars.ENV_PROD }}" > .env

      - name: Build project
        run: pnpm run build --if-present

      - run: pm2 startOrRestart ecosystem.config.cjs
